### ISSUE TITLE
MySlowTranCapture unable to write log 

### ISSUE THREAD

**Issue by laalesh** [yoshinorim/MySlowTranCapture#1]
Hi,

Really this is a great stuff for which we are waiting from long time.

But while using MySlowTranCapture it is not logging the records.

Below are the steps I have executed:

Session 1: 

/usr/local/bin/myslowtrancapture -i eth0 -t 1000
Monitoring eth0 interface..
Listening port 3306..
Logging transactions that take more than 1000 milliseconds..

Session 2:

mysql> begin;
mysql> select \* from t1 where id = 2 for update;

Session 3:

mysql> begin;
mysql> update t1 set name = 'ccc' where id = 1;
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction

Session 1: 

/usr/local/bin/myslowtrancapture -i eth0 -t 1000
Monitoring eth0 interface..
Listening port 3306..
Logging transactions that take more than 1000 milliseconds..

MySlowTranCapture does not prints any thing in session 1.

Please help in using this tool.

Thanks,
Laalesh

**Comment by yoshinorim** [comment]
Hi,

Did you run session 2,3 from remote hosts?
MySlowTranCapture uses libpcap (same as tcpdump) to capture packets, so all mysql packets 
should pass the target network interface.

**Comment by laalesh** [comment]
nope, all the session are from localhost.

**Comment by yoshinorim** [comment]
As commented above, please try the same thing from remote clients.

**Comment by laalesh** [comment]
yep, its working, thank you for your support.
